---
image: williamyeh/ansible:ubuntu16.04

before_script:
#  - apt-get update -qq
#  - apt-get install -y git python-apt
#  - pip install -r requirements.txt
#  - ansible-galaxy install -r tests/requirements.yml
#  - cp extra_vars.yml.sample extra_vars.yml

validate:
  script:
    - molecule lint
    - cd tests
    - ansible-playbook test.yml -i inventory --check

test_skyway_edge_vm:
  script:
    - ansible-playbook tests/test.yml -i tests/inventory

test_skyway_edge_vm_docker:
  image: docker:latest
  services:
    - docker:dind
  before_script:
  script:
    - docker build -t $CI_REGISTRY_IMAGE:latest .
    - docker run $CI_REGISTRY_IMAGE:latest
