---
stages:
  - lint
  - test_role
  - test_docker

language: python

sudo: required

services:
  - docker

addons:
  apt:
    update: true

before_install:
  - echo $PATH

jobs:
  include:
    - stage: lint
      script:
        - molecule lint
        - ansible-playbook tests/test.yml -i tests/inventory --check
    - stage: test_role
      script:
        - >
          ansible-playbook tests/test.yml -i tests/inventory
          --extra-vars "govc_bindir=/home/travis/.local/bin"
    - stage: test_docker
      script:
        - docker build -t vmware/cloud-to-edge-vm .
        - docker run -it --rm vmware/cloud-to-edge-vm
