# Copyright © 2018 VMware, Inc. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
---
# These tasks set up dependencies in order to launch VMs

- name: Check if govc installed
  shell: command -v govc >/dev/null 2>&1
  register: is_govc_exist
  ignore_errors: true
  when: govc is not defined

- name: Download govc
  block:
    - name: Define govc build
      set_fact: govc_build="linux_amd64"
      when: ansible_os_family == "Debian"

    - name: Define govc build (OSX)
      set_fact: govc_build="darwin_amd64"
      when: ansible_os_family == "Darwin"

    - name: Download govc
      get_url:
        url: "https://github.com/vmware/govmomi/releases/download/v\
          {{ govc_version }}/govc_{{ govc_build }}.gz"
        dest: "/tmp/govc.gz"
      register: download_govc

    - name: Unzip govc
      command: gunzip "/tmp/govc.gz"

    - name: Move govc into place
      command: mv /tmp/govc "{{ govc_bindir }}/govc"

    - name: Set govc perms
      file:
        path: "{{ govc_bindir }}/govc"
        mode: "+x"
      when:
        - download_govc.changed
        - not download_govc.failed
      tags:
        - skip_ansible_lint

    - name: Define govc path
      set_fact: govc="{{ govc_bindir }}/govc"
  when:
    - govc is not defined
    - is_govc_exist is defined and is_govc_exist.failed

- name: debug govc
  debug: msg="using govc {{ is_govc_exist }}"

- name: Use found govc
  set_fact: govc="govc"
  when:
    - govc is not defined
    - is_govc_exist is defined and not is_govc_exist.failed

- name: Ensure root .ssh directory exists
  file:
    path: "{{ansible_env.HOME}}/.ssh"
    state: directory
    mode: 0700

- name: Create private key file for edges
  copy:
    content: "{{ skyway_edge_vm_ssh_priv_key }}"
    dest: "{{ansible_env.HOME}}/.ssh/id_rsa_edges"
    mode: 0600
  when:
    - skyway_edge_vm_ssh_priv_key is defined
