# Copyright © 2018 VMware, Inc. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
---
# These tasks launch a given VM to act as an Edge Gateway

# jq -n --arg userdata "$userdata" --arg network "$network"
#   -f bootstrap-spec.json > bootstrap-spec.edited.json
# govc import.ova -options=bootstrap-spec.edited.json -name=$vm bootstrap.ova
# govc vm.change -vm $vm -nested-hv-enabled=true
# govc vm.change -vm $vm -m=${memory}
# govc vm.change -vm $vm -c=${cpus}
# govc vm.disk.change -vm $vm -size ${disk}
# vm_path="$(govc find / -type m -name "$vm")"

- name: Set suffix for Azure edges
  set_fact:
    vm_suffix: "az"
  when:
    - azure_iot_edge_names is defined
    - skyway_edge.edge_group in azure_iot_edge_names

- name: Set suffix for GreenGrass Cores
  set_fact:
    vm_suffix: "aws"
  when:
    - greengrass_group_names is defined
    - skyway_edge.edge_group in greengrass_group_names

- name: Establish VM name
  set_fact:
    vm_name: >-
      {{ skyway_edge_vm_basename }}-{{ vm_suffix }}-{{ skyway_edge.edge_group }}
  when:
    - skyway_edge_vm_basename is defined
    - vm_suffix is defined
    - skyway_edge is defined and skyway_edge.edge_group is defined

- name: Establish VM network (default)
  set_fact: vm_network="{{ skyway_edge_vm_network }}"
  when:
    - skyway_edge_vm_network is defined

- name: Establish VM network
  set_fact: vm_network="{{ skyway_edge.vm_network }}"
  when:
    - skyway_edge is defined and skyway_edge.vm_network is defined

- name: Get vcenter details
  command: >
    {{ govc }} about
  environment:
    GOVC_URL: "{{ skyway_edge.vcenter_host }}"
    GOVC_USERNAME: "{{ skyway_edge.vcenter_usr }}"
    GOVC_PASSWORD: "{{ skyway_edge.vcenter_pwd }}"
    GOVC_DATACENTER: "{{ skyway_edge.vcenter_datacenter }}"
    GOVC_DATASTORE: "{{ skyway_edge.vcenter_datastore }}"
    GOVC_CLUSTER: "{{ skyway_edge.vcenter_cluster }}"
    GOVC_RESOURCE_POOL: "{{ skyway_edge.vcenter_rp }}"
    GOVC_INSECURE: "{{ skyway_edge.vcenter_insecure }}"
  register: govc_about
  when: govc is defined

- name: Search for expected VM
  command: >
    {{ govc }} find / -type m -name {{ vm_name | quote }}
  environment:
    GOVC_URL: "{{ skyway_edge.vcenter_host }}"
    GOVC_USERNAME: "{{ skyway_edge.vcenter_usr }}"
    GOVC_PASSWORD: "{{ skyway_edge.vcenter_pwd }}"
    GOVC_DATACENTER: "{{ skyway_edge.vcenter_datacenter }}"
    GOVC_DATASTORE: "{{ skyway_edge.vcenter_datastore }}"
    GOVC_CLUSTER: "{{ skyway_edge.vcenter_cluster }}"
    GOVC_RESOURCE_POOL: "{{ skyway_edge.vcenter_rp }}"
    GOVC_INSECURE: "{{ skyway_edge.vcenter_insecure }}"
  register: govc_find_vm
  when: govc is defined

- name: Set VM path fact
  set_fact:
    vm_path: ""
  when:
    - govc_find_vm is defined and not govc_find_vm.failed
    - govc_find_vm.stdout is defined
    - vm_name not in govc_find_vm.stdout

- name: Set VM path fact
  set_fact:
    vm_path: "{{ govc_find_vm.stdout }}"
  when:
    - govc_find_vm is defined and not govc_find_vm.failed
    - govc_find_vm.stdout is defined
    - vm_name in govc_find_vm.stdout

- name: Detect ARM cluster
  set_fact:
    is_arm: false

# For the moment, we use the cluster naming convention "*_arm" to "detect"
# an ARM CPU host.
# TODO: Once the ARM ESX goes GA, replace with a proper check.
- name: Detect ARM cluster
  set_fact:
    is_arm: true
  when:
    - skyway_edge.vcenter_cluster is match(".*_(arm|ARM)$")

- name: Name the OVA
  set_fact:
    local_ova_name: "skyway-edge-{{ (is_arm) | ternary('arm','amd') }}64.ova"

- name: VM not found for edge, need to make it
  block:
    - name: Download base OVA
      get_url:
        url: "{{ binary_webserver }}/{{ base_ova_name }}"
        dest: "/tmp/{{ local_ova_name }}"
      register: download_base_ova
      when:
        - binary_webserver is defined
        - base_ova_name is defined
        - not is_arm
      retries: 10
      delay: 120
      until: not download_base_ova.failed

    - name: Download base OVA from internet
      get_url:
        url: "{{ base_ova_origin }}"
        dest: "/tmp/{{ local_ova_name }}"
      register: download_base_ova_origin
      when:
        - base_ova_origin is defined
        - download_base_ova is undefined or not download_base_ova.changed
        - not is_arm
      retries: 10
      delay: 120
      until: not download_base_ova_origin.failed
      tags:
        - skip_ansible_lint

    - name: Download base OVA - ARM
      get_url:
        url: "{{ binary_webserver }}/{{ base_ova_name_arm }}"
        dest: "/tmp/{{ local_ova_name }}"
      register: download_base_ova_arm
      when:
        - binary_webserver is defined
        - base_ova is defined
        - is_arm
      retries: 10
      delay: 120
      until: not download_base_ova_arm.failed

    - name: Download base OVA from internet - ARM
      get_url:
        url: "{{ base_ova_origin_arm }}"
        dest: "/tmp/{{ local_ova_name }}"
      register: download_base_ova_arm_origin
      when:
        - base_ova_origin_arm is defined
        - download_base_ova_arm is undefined or
          not download_base_ova_arm.changed
        - is_arm
      retries: 10
      delay: 120
      until: not download_base_ova_arm_origin.failed
      tags:
        - skip_ansible_lint

    - name: create temporary directory for VM info
      tempfile:
        state: directory
        suffix: govc
      register: govc_temp

    - name: debug generated file path
      debug: msg="Generating files at {{ govc_temp }}"

    - name: debug edge to create
      debug: var="skyway_edge"

    - name: Template out vm userdata
      template:
        src: user-data.yml.j2
        dest: "{{ govc_temp.path }}/user-data.yml"
      when: govc_temp.path is defined

    - name: Encode userdata
      command: base64 "{{ govc_temp.path }}/user-data.yml"
      register: base64_userdata
      when:
        - govc_temp.path is defined

    - name: Set userdata fact
      set_fact: userdata="{{ base64_userdata.stdout }}"
      when:
        - base64_userdata is defined
        - base64_userdata.failed is defined
        - not base64_userdata.failed

    - name: Template out vm spec
      template:
        src: vm-spec.json.j2
        dest: "{{ govc_temp.path }}/vm-spec.json"
      when:
        - userdata is defined

    - name: Import ova
      command: >
        {{ govc }} import.ova -options="{{ govc_temp.path }}/vm-spec.json"
        -name={{ vm_name|quote }}
        "/tmp/{{ local_ova_name }}"
      environment:
        GOVC_URL: "{{ skyway_edge.vcenter_host }}"
        GOVC_USERNAME: "{{ skyway_edge.vcenter_usr }}"
        GOVC_PASSWORD: "{{ skyway_edge.vcenter_pwd }}"
        GOVC_DATACENTER: "{{ skyway_edge.vcenter_datacenter }}"
        GOVC_DATASTORE: "{{ skyway_edge.vcenter_datastore }}"
        GOVC_CLUSTER: "{{ skyway_edge.vcenter_cluster }}"
        GOVC_RESOURCE_POOL: "{{ skyway_edge.vcenter_rp }}"
        GOVC_INSECURE: "{{ skyway_edge.vcenter_insecure }}"
      register: govc_import_ova
      when: govc is defined and govc_temp.path is defined
      retries: 10
      delay: 120
      until: not govc_import_ova.failed

    - name: Now search for created VM
      command: >
        {{ govc }} find / -type m -name {{ vm_name | quote }}
      environment:
        GOVC_URL: "{{ skyway_edge.vcenter_host }}"
        GOVC_USERNAME: "{{ skyway_edge.vcenter_usr }}"
        GOVC_PASSWORD: "{{ skyway_edge.vcenter_pwd }}"
        GOVC_DATACENTER: "{{ skyway_edge.vcenter_datacenter }}"
        GOVC_DATASTORE: "{{ skyway_edge.vcenter_datastore }}"
        GOVC_CLUSTER: "{{ skyway_edge.vcenter_cluster }}"
        GOVC_RESOURCE_POOL: "{{ skyway_edge.vcenter_rp }}"
        GOVC_INSECURE: "{{ skyway_edge.vcenter_insecure }}"
      register: govc_find_vm
      when: govc is defined

    - name: Set VM path fact
      set_fact:
        vm_path: "{{ govc_find_vm.stdout }}"
      when:
        - govc_find_vm is defined and not govc_find_vm.failed
        - vm_name in govc_find_vm.stdout
  when:
    - vm_path is not defined or not vm_path or vm_path == ""
    - govc_find_vm.stdout is defined

- name: debug found VM
  debug: msg="Found edge VM {{ vm_path }}"
  when: vm_path is defined

- name: Is VM powered on?
  command: >
    {{ govc }} object.collect -s "{{ vm_path }}" runtime.powerState
  environment:
    GOVC_URL: "{{ skyway_edge.vcenter_host }}"
    GOVC_USERNAME: "{{ skyway_edge.vcenter_usr }}"
    GOVC_PASSWORD: "{{ skyway_edge.vcenter_pwd }}"
    GOVC_DATACENTER: "{{ skyway_edge.vcenter_datacenter }}"
    GOVC_DATASTORE: "{{ skyway_edge.vcenter_datastore }}"
    GOVC_CLUSTER: "{{ skyway_edge.vcenter_cluster }}"
    GOVC_RESOURCE_POOL: "{{ skyway_edge.vcenter_rp }}"
    GOVC_INSECURE: "{{ skyway_edge.vcenter_insecure }}"
  register: is_vm_on
  when: govc is defined and vm_path is defined

- name: Power it on
  command: >
    {{ govc }} vm.power -on {{ vm_name|quote }}
  environment:
    GOVC_URL: "{{ skyway_edge.vcenter_host }}"
    GOVC_USERNAME: "{{ skyway_edge.vcenter_usr }}"
    GOVC_PASSWORD: "{{ skyway_edge.vcenter_pwd }}"
    GOVC_DATACENTER: "{{ skyway_edge.vcenter_datacenter }}"
    GOVC_DATASTORE: "{{ skyway_edge.vcenter_datastore }}"
    GOVC_CLUSTER: "{{ skyway_edge.vcenter_cluster }}"
    GOVC_RESOURCE_POOL: "{{ skyway_edge.vcenter_rp }}"
    GOVC_INSECURE: "{{ skyway_edge.vcenter_insecure }}"
  when:
    - is_vm_on.stdout is defined
    - is_vm_on.stdout != "poweredOn"

- name: Wait for VM to get an IP
  command: >
    {{ govc }} vm.ip -a -v4 {{ vm_name|quote }}
  environment:
    GOVC_URL: "{{ skyway_edge.vcenter_host }}"
    GOVC_USERNAME: "{{ skyway_edge.vcenter_usr }}"
    GOVC_PASSWORD: "{{ skyway_edge.vcenter_pwd }}"
    GOVC_DATACENTER: "{{ skyway_edge.vcenter_datacenter }}"
    GOVC_DATASTORE: "{{ skyway_edge.vcenter_datastore }}"
    GOVC_CLUSTER: "{{ skyway_edge.vcenter_cluster }}"
    GOVC_RESOURCE_POOL: "{{ skyway_edge.vcenter_rp }}"
    GOVC_INSECURE: "{{ skyway_edge.vcenter_insecure }}"
  register: govc_vm_ip
  when:
    - not is_arm

- name: Remember VM IP
  set_fact:
    vm_ip: "{{ govc_vm_ip.stdout }}"
  when:
    - govc_vm_ip.stdout is defined and not govc_vm_ip.failed

- name: Get VM info (ARM)
  command: >
    {{ govc }} vm.info -json {{ vm_name|quote }}
  environment:
    GOVC_URL: "{{ skyway_edge.vcenter_host }}"
    GOVC_USERNAME: "{{ skyway_edge.vcenter_usr }}"
    GOVC_PASSWORD: "{{ skyway_edge.vcenter_pwd }}"
    GOVC_DATACENTER: "{{ skyway_edge.vcenter_datacenter }}"
    GOVC_DATASTORE: "{{ skyway_edge.vcenter_datastore }}"
    GOVC_CLUSTER: "{{ skyway_edge.vcenter_cluster }}"
    GOVC_RESOURCE_POOL: "{{ skyway_edge.vcenter_rp }}"
    GOVC_INSECURE: "{{ skyway_edge.vcenter_insecure }}"
  register: vm_info
  when:
    - is_arm

- name: Set VM info
  set_fact:
    vm: "{{ vm_info.stdout | from_json }}"
  when:
    vm_info.changed
  tags:
    - skip_ansible_lint

- name: Debug VM info
  debug:
    var: vm
  when:
    vm_info.changed
  tags:
    - skip_ansible_lint

- name: Enable esx guest IP hack (ARM)
  command: >
    {{ govc }} host.esxcli system settings advanced set -o /Net/GuestIPHack -i 1
  environment:
    GOVC_URL: "{{ skyway_edge.vcenter_host }}"
    GOVC_USERNAME: "{{ skyway_edge.vcenter_usr }}"
    GOVC_PASSWORD: "{{ skyway_edge.vcenter_pwd }}"
    GOVC_DATACENTER: "{{ skyway_edge.vcenter_datacenter }}"
    GOVC_DATASTORE: "{{ skyway_edge.vcenter_datastore }}"
    GOVC_CLUSTER: "{{ skyway_edge.vcenter_cluster }}"
    GOVC_RESOURCE_POOL: "{{ skyway_edge.vcenter_rp }}"
    GOVC_INSECURE: "{{ skyway_edge.vcenter_insecure }}"
  register: vm_info
  when:
    - is_arm == "Never gonna happen."

- name: Wait for VM to get an IP (ARM)
  command: >
    {{ govc }} vm.ip -esxcli=true {{ vm_name|quote }}
  environment:
    GOVC_URL: "{{ skyway_edge.vcenter_host }}"
    GOVC_USERNAME: "{{ skyway_edge.vcenter_usr }}"
    GOVC_PASSWORD: "{{ skyway_edge.vcenter_pwd }}"
    GOVC_DATACENTER: "{{ skyway_edge.vcenter_datacenter }}"
    GOVC_DATASTORE: "{{ skyway_edge.vcenter_datastore }}"
    GOVC_CLUSTER: "{{ skyway_edge.vcenter_cluster }}"
    GOVC_RESOURCE_POOL: "{{ skyway_edge.vcenter_rp }}"
    GOVC_INSECURE: "{{ skyway_edge.vcenter_insecure }}"
  register: govc_vm_ip
  when:
    - is_arm

- name: Remember VM IP
  set_fact:
    vm_ip: "{{ govc_vm_ip.stdout }}"
  when:
    - vm_ip is undefined
    - govc_vm_ip.stdout is defined and not govc_vm_ip.failed

- name: debug VM IP
  debug: msg="Edge VM {{ vm_path }} has IP {{ vm_ip }}"
  when: vm_path is defined and vm_ip is defined

- name: Add new host to group 'greengrass-core' with core ID set.
  add_host:
    name: "{{ vm_ip }}"
    groups: greengrass-core
    ansible_user: "{{ skyway_edge_vm_user }}"
    ansible_ssh_private_key_file: "{{ansible_env.HOME}}/.ssh/id_rsa_edges"
    ansible_become: true
    greengrass_core_id: "{{ skyway_edge.edge_group }}_Core"
  when:
    - vm_ip is defined
    - greengrass_group_names is defined
    - skyway_edge.edge_group in greengrass_group_names

- name: Add new host to group 'azure-edge' with Edge name set.
  add_host:
    name: "{{ vm_ip }}"
    groups: azure-edge
    ansible_user: "{{ skyway_edge_vm_user }}"
    ansible_ssh_private_key_file: "{{ansible_env.HOME}}/.ssh/id_rsa_edges"
    ansible_become: true
    azure_edge_name: "{{ skyway_edge.edge_group }}"
  when:
    - vm_ip is defined
    - azure_iot_edge_names is defined
    - skyway_edge.edge_group in azure_iot_edge_names
