# Copyright © 2018 VMware, Inc. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
---
# These tasks launch a given VM to act as an Edge Gateway

# jq -n --arg userdata "$userdata" --arg network "$network"
#   -f bootstrap-spec.json > bootstrap-spec.edited.json
# govc import.ova -options=bootstrap-spec.edited.json -name=$vm bootstrap.ova
# govc vm.change -vm $vm -nested-hv-enabled=true
# govc vm.change -vm $vm -m=${memory}
# govc vm.change -vm $vm -c=${cpus}
# govc vm.disk.change -vm $vm -size ${disk}
# vm_path="$(govc find / -type m -name "$vm")"

- name: Download base OVA
  get_url:
    url: "{{ binary_webserver }}/{{ base_ova }}"
    dest: "/tmp/skyway-edge-amd64.ova"
  register: download_base_ova
  when:
    - binary_webserver is defined
    - base_ova is defined

- name: Download base OVA from internet
  get_url:
    url: "{{ base_ova_origin }}"
    dest: "/tmp/skyway-edge-amd64.ova"
  register: download_base_ova_origin
  when:
    - base_ova_origin is defined
    - download_base_ova is undefined or not download_base_ova.changed
  tags:
    - skip_ansible_lint

- name: create temporary directory for VM info
  tempfile:
    state: directory
    suffix: govc
  register: govc_temp

- name: debug generated file path
  debug: msg="Generating files at {{ govc_temp }}"

- name: debug edge to create
  debug: var="skyway_edge"

- name: Template out vm userdata
  template:
    src: user-data.yml.j2
    dest: "{{ govc_temp.path }}/user-data.yml"

- name: Encode userdata
  command: base64 "{{ govc_temp.path }}/user-data.yml"
  register: base64_userdata
  when:
    - userdata is not defined

- name: Set userdata fact
  set_fact: userdata="{{ base64_userdata.stdout }}"
  when:
    - base64_userdata is defined and not base64_userdata.failed

- name: Template out vm spec
  template:
    src: vm-spec.json.j2
    dest: "{{ govc_temp.path }}/vm-spec.json"
  when:
    - userdata is defined

- name: Import ova
  command: >
    {{ govc }} import.ova -options="{{ govc_temp.path }}/vm-spec.json"
    -name={{ vm_name|quote }}
    "/tmp/skyway-edge-amd64.ova"
  environment:
    GOVC_URL: "{{ skyway_edge.vcenter_host }}"
    GOVC_USERNAME: "{{ skyway_edge.vcenter_usr }}"
    GOVC_PASSWORD: "{{ skyway_edge.vcenter_pwd }}"
    GOVC_DATACENTER: "{{ skyway_edge.vcenter_datacenter }}"
    GOVC_DATASTORE: "{{ skyway_edge.vcenter_datastore }}"
    GOVC_CLUSTER: "{{ skyway_edge.vcenter_cluster }}"
    GOVC_RESOURCE_POOL: "{{ skyway_edge.vcenter_rp }}"
  register: govc_import_ova
  when: govc is defined
