---
# tasks file for ansible-role-cloud-to-edge-vm
# Copyright © 2018 VMware, Inc. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
# These tasks loop over the VMs to create.

- include_tasks: c2e-vm.yml
  loop: "{{ skyway_edges[skyway_edge_start-1:skyway_edge_end] }}"
  loop_control:
    loop_var: skyway_edge
  when:
    - skyway_edge_start is defined
    - skyway_edge_end is defined

- include_tasks: c2e-vm.yml
  loop: "{{ skyway_edges }}"
  loop_control:
    loop_var: skyway_edge
  when:
    - skyway_edge_start is undefined
    - skyway_edge_end is undefined
